- name: Ensure git and ansible are installed for ansible-pull
  ansible.builtin.package:
    name:
      - ufw
    state: present

- name: Enable UFW and deny everything
  community.general.ufw:
    state: enabled
    policy: deny
    direction: incoming
    logging: 'medium'

- name: Allow SSH through UFW
  community.general.ufw:
    rule: allow
    name: SSH

- name: Create gamemasters group
  ansible.builtin.group:
    name: gamemasters
    state: present
  register: group_gamemasters

- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    group: "{{ group_gamemasters.name }}"
    groups: "{{ item.groups | default([]) }}"
    state: present
    create_home: true
    shell: /bin/ash
  loop: "{{ users }}"
- name: Add keys to users
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', '{}.pub'.format(item.name)) }}"
  loop: "{{ users }}"
