- name: Ensure utility packages are installed
  ansible.builtin.package:
    name:
      - doas
      - firewalld
      - firewalld-openrc
    state: present

- name: Enable and start firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Open SSH
  ansible.posix.firewalld:
    service: ssh
    permanent: true
    state: enabled
    immediate: true

- name: Create gamemasters group
  ansible.builtin.group:
    name: gamemasters
    state: present
  register: group_gamemasters

- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    group: "{{ group_gamemasters.name }}"
    groups: "{{ item.groups }}"
    state: present
    create_home: true
    shell: /bin/ash
  loop: "{{ users }}"
- name: Add keys to users
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', '{}.pub'.format(item.name)) }}"
  loop: "{{ users }}"
