---
- name: Panel
  hosts: panel
  remote_user: "{{ ansible_user }}"
  roles:
    - common
    - gitops

- name: Wing
  hosts: wings
  remote_user: "{{ ansible_user }}"
  roles:
    - common
    - gitops
