- name: NJoy GitOps Configuration
  hosts: localhost
  connection: local
  become: true
  vars:
    users:
      - name: alice
        groups:
          - wheel
        
    podman_containers:
      - name: cobblemon
        image: ghcr.io/vespion/njoy/cobblemon:1.2.0
        volumes:
          # A named volume (Ansible will create this automatically)
          - cobblemon-world:/srv/minecraft/world
        ports:
          - "25565:25565/tcp"
          - "24454:24454/udp"
  roles:
    - admin
    # - gitops
    - podman
    - containers