---
- name: Panel Configuration
  become: true
  remote_user: "{{ ansible_user }}"
  hosts: panel
  roles:
    - panel

- name: Id configuration
  hosts: id
  become: true
  remote_user: "{{ ansible_user }}"
  roles:
    - kanidm
