---
# THIS WILL NOT BE AUTO-UPDATED BY ANSIBLE-PULL!
# Ensure you install these manually on the host before running ansible-pull via ansible-galaxy
collections:
  - name: community.general
  - name: ansible.posix
roles:
  - name: caddy_ansible.caddy_ansible
