---
- name: Create web server group
  ansible.builtin.group:
    name: websrv
    system: true
    state: present
  register: caddy_service_group

- name: Create caddy user
  ansible.builtin.user:
    name: caddy
    shell: /usr/sbin/nologin
    group: "{{ caddy_service_group.name }}"
    system: true
    create_home: true
    comment: "Caddy web server user"
  register: caddy_service_user

- name: Copy shared error pages
  ansible.builtin.copy:
    src: "files/anime-http/dist/"
    dest: /var/www/shared_status_pages
    owner: "{{ caddy_service_user.name }}"
    group: "{{ caddy_service_group.name }}"
    mode: "644"

- name: Create enabled sites directory
  ansible.builtin.file:
    dest: /etc/caddy/sites-enabled
    state: directory
    owner: "{{ caddy_service_user.name }}"
    group: "{{ caddy_service_group.name }}"
    mode: "775"
  register: caddy_sites_enabled_dir

- name: Install caddy role
  ansible.builtin.import_role:
    name: caddy_ansible.caddy_ansible
  vars:
    caddy_user: "{{ caddy_service_user.name }}"
    caddy_config: "{{ lookup('file', 'files/main.Caddyfile') }}"
    caddy_home: "{{ caddy_service_user.home }}"

- name: Open firewall for caddy
  community.general.ufw:
    rule: allow
    name: WWW Full
