---
- name: Ensure SSL private key exists
  community.crypto.openssl_privatekey:
    path: "{{ kanidm_cert_private_key_path }}"
    size: 2048
    mode: "0600"

- name: Generate Certificate Signing Request (CSR) with SANs
  community.crypto.openssl_csr:
    path: "{{ kanidm_cert_csr_path }}"
    privatekey_path: "{{ kanidm_cert_private_key_path }}"
    common_name: "{{ kanidm_cert_common_name }}"
    subject_alt_name: "{{ kanidm_cert_subject_alt_names }}"

- name: Checkif certificate already exists
  ansible.builtin.stat:
    path: "{{ kanidm_cert_output_path }}"
  register: kanidm_cert_stats

- name: Gather current certificate details if it already exists
  community.crypto.x509_certificate_info:
    path: "{{ kanidm_cert_output_path }}"
  register: kanidm_cert_info
  ignore_errors: true
  when: kanidm_cert_stats.stat.exists

- name: Generate or renew TLS certificate if missing, expired, or expiring soon
  notify: Restart kanidm
  community.crypto.x509_certificate:
    path: "{{ kanidm_cert_output_path }}"
    privatekey_path: "{{ kanidm_cert_private_key_path }}"
    csr_path: "{{ kanidm_cert_csr_path }}"
    provider: selfsigned
    selfsigned_not_after: "+365d"
    force: >-
      {{
        not kanidm_cert_stats.stat.exists or
        cert_info.expired | default(true) or
        ((cert_info.not_after | to_datetime('%Y%m%d%H%M%SZ') -
          ansible_facts["date_time"].iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ')).days < 30)
      }}
