---
- name: Modify srv traversal permissions
  ansible.builtin.file:
    dest: /srv
    state: directory
    mode: "775"

- name: Create panel server directory
  ansible.builtin.file:
    dest: /srv/panel
    state: directory
    owner: "{{ caddy_service_user.name }}"
    group: "{{ caddy_service_group.name }}"
    mode: "775"
  register: panel_dir

- name: Deploy maintenance page
  ansible.builtin.copy:
    src: "files/Caddyfile"
    dest: "{{ panel_dir.path }}/Caddyfile"
    owner: "{{ caddy_service_user.name }}"
    group: "{{ caddy_service_group.name }}"
    mode: "644"

- name: Enable maintenance page
  become: true
  become_user: caddy
  notify: Reload caddy
  ansible.builtin.file:
    src: "{{ panel_dir.path }}/Caddyfile"
    dest: "{{ caddy_sites_enabled_dir.path }}/panel.caddy"
    mode: "644"
    force: true
    state: link
