---
- name: Install packages
  ansible.builtin.package:
    name:
      - fail2ban-server
    state: present

- name: Copy configuration
  ansible.builtin.copy:
    src: "files/fail2ban.conf"
    dest: /etc/fail2ban/fail2ban.local
    owner: root
    group: root
    mode: "644"

- name: Insert IPv4 rate limit rules
  ansible.builtin.blockinfile:
    path: /etc/ufw/before.rules
    marker: "# {mark} ANSIBLE MANAGED BLOCK - UFW RATE LIMITS IPv4"
    insertbefore: "^COMMIT"
    block: "{{ lookup('ansible.builtin.template', 'templates/adaptive.ipv4.rules.j2') }}"
    backup: true
  notify: &ufw_reload_handler Reload ufw

- name: Insert IPv6 rate limit rules
  ansible.builtin.blockinfile:
    path: /etc/ufw/before6.rules
    marker: "# {mark} ANSIBLE MANAGED BLOCK - UFW RATE LIMITS IPv6"
    insertbefore: "^COMMIT"
    block: "{{ lookup('ansible.builtin.template', 'templates/adaptive.ipv6.rules.j2') }}"
    backup: true
  notify: *ufw_reload_handler

- name: Copy synflood filter
  ansible.builtin.copy:
    src: "files/synflood.conf"
    dest: /etc/fail2ban/filter.d/synflood.conf
    owner: root
    group: root
    mode: "644"

- name: Copy connlimit filter
  ansible.builtin.copy:
    src: "files/connlimit.conf"
    dest: /etc/fail2ban/filter.d/connlimit.conf
    owner: root
    group: root
    mode: "644"

- name: Copy jail configs
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/fail2ban/jail.d/
    owner: root
    group: root
    mode: "644"
  with_fileglob:
    - "files/*.local"

- name: Add mangle rules (ipv4)
  notify: *ufw_reload_handler
  ansible.builtin.blockinfile:
    dest: /etc/ufw/before.rules
    block: "{{ lookup('file', 'files/mangle.ipv4.rules') }}"

- name: Add mangle rules (ipv6)
  notify: *ufw_reload_handler
  ansible.builtin.blockinfile:
    dest: /etc/ufw/before6.rules
    block: "{{ lookup('file', 'files/mangle.ipv6.rules') }}"

- name: Add kernel hardening rules
  notify: *ufw_reload_handler
  ansible.builtin.blockinfile:
    dest: /etc/ufw/sysctl.conf
    block: "{{ lookup('file', 'files/sysctl.conf') }}"
