---
- name: Bootstrap Fedora
  when: ansible_facts['pkg_mgr'] == "dnf"
  ansible.builtin.include_tasks:
    file: dnf.yml
    apply:
      become: true
      become_user: root

- name: Sync admin SSH keys
  ansible.posix.authorized_key:
    user: "{{ admin_user }}"
    state: present
    key: https://github.com/vespion.keys
