---
- name: Restart Kanidm unixd
  ansible.builtin.systemd:
    name: kanidm-unixd
    state: restarted

- name: Apply Authselect Profile
  ansible.builtin.command:
    cmd: authselect apply-changes
  changed_when: true

- name: Restart SSHD
  ansible.builtin.systemd:
    name: sshd
    state: restarted
