on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - servers/minecraft/cobblemon/**
      - servers/minecraft/entrypoint.sh
      - servers/minecraft/eula.txt

name: Build and Attest (Cobblemon)

jobs:
  build-and-publish-cobblemon:
    uses: ./.github/workflows/container_build.yaml
    with:
      working_directory: servers/minecraft/cobblemon
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write