on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string

name: Container Builder

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Install earthbuild
        uses: EarthBuild/actions-setup@f4d20223e70dbb43b5fc08c4d857ab9cf0dbf3ae # v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 1
      
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Image
        working-directory: ${{ inputs.working_directory }}
        id: build-image
        run: |
          earthly --push -a +image-with-attestation-meta/* ./out/
          echo "digest=$(cat ./out/digest.txt)" >> $GITHUB_OUTPUT
          echo "name=$(cat ./out/name.txt)" >> $GITHUB_OUTPUT

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4
        with:
          subject-name: ${{ steps.build-image.outputs.name }}
          subject-digest: ${{ steps.build-image.outputs.digest }}
      